## These have to be uploaded to each environment as a secret
# gcloud secrets create ${ENV}-env-overrides --data-file="./config/${ENV}.yml"
file: simple.yml
postgresql:
  debug: false
  connection:
    host: database
  automigrate: true
  autoseed: true
openai: 
  key: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXX #overriden by github
  cachePath: ./.cicd/cache
  stream: false
storage:
  bucket: docker-bucket
  apiEndpoint: http://storage:9023
  baseUrl: storage:9023
authentication:
  superadmin: 
    - superadmin@example.com