name: "API:Test and Deploy"

on:
  push: 
    branches:
      - 'develop'
      - 'test'
      - 'production'
      - 'main'
    paths:
      - 'apps/api/**'

  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:

    # TESTING
    # api-contract-test:
    #   secrets: inherit
    #   uses: ./.github/workflows/api.job.contract-test.yml

    # web-test:
    #   secrets: inherit
    #   uses: ./.github/workflows/interfaces.web.test.yml

    # plugin-test:
    #   secrets: inherit
    #   uses: ./.github/workflows/plugin.job.test.yml


    # VERSIONING
    versioning:
      needs: api-contract-test, web-test, plugin-test
      secrets: inherit
      uses: ./.github/workflows/versioning.yml


    # DEPLOYMENTS
    # api-deploy:
    #   # needs: contract-test
    #   secrets: inherit
    #   uses: ./.github/workflows/api.job.deploy-cloudrun.yml


    

    pull-request:
      needs: deploy
      secrets: inherit
      uses: ./.github/workflows/api.job.create-pr.yml