name: "API:Test"

on:
  push: 
    branches: 
      - '*'
      - '**'
      - '*/*'
      - '!develop'
      - '!test'
      - '!production'
      - '!main'
    paths:
      - 'apps/api/**'
  pull_request:
    paths:
      - 'apps/api/**'

  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:
  contract-test:
    name: Contract Tests
    secrets: inherit
    uses: ./.github/workflows/api.job.contract-test.yml