name: Test and Deploy

on:
  push: 
    branches:
      - 'develop'
      - 'test'
      - 'production'
      - 'main'
    paths:
      - 'apps/api/**'

  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:
    # contract-test:
    #   secrets: inherit
    #   uses: ./.github/workflows/api.job.contract-test.yml
    deploy:
      # needs: contract-test
      secrets: inherit
      uses: ./.github/workflows/api.job.deploy-cloudrun.yml