name: "API:Job:CreatePR"

on:
  workflow_call:
    inputs:
        version:
          description: 'The version to deploy'
          required: true
          type: string
  workflow_dispatch:

jobs:
  deploy:
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    env: 
      ENV: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}        
    runs-on: ubuntu-latest
    steps:
        - name: Create Pull Request to Test
          if: github.ref_name == 'develop' && success()
          uses: peter-evans/create-pull-request@v5
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base: develop
            branch: test
            title: 'Deploy ${{ inputs.version }} to Test'
            body: 'This PR is automatically created after a successful deployment from develop to test.'

        - name: Create Pull Request to Main
          if: github.ref_name == 'test' && success()
          uses: peter-evans/create-pull-request@v5
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base: test
            branch: main
            title: 'Deploy ${{ inputs.version }} to Main'
            body: 'This PR is automatically created after a successful deployment from test to main.'