name: API:Contract Tests

on:
  workflow_call:
  workflow_dispatch:

env:
  WORKDIR: "./apps/api"
  DOCKER_REGISTRY: https://ghcr.io # the github registry
  FILE: "./test/contracts/contract.docker-compose.yml"

jobs:
  blueprint:
    name: "API:Contract:Blueprint Tests"
    env:
      CONTRACT_TYPE: "blueprint"
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start stack
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
          echo CONTRACT_TYPE=${{ env.CONTRACT_TYPE }} >> .env
          docker compose --env-file ./.env -f ${{ env.FILE }} up --exit-code-from newman
        
      - name: Stop stacks
        if: always()
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker compose -f ${{ env.FILE }} down
  
  plugin-loader:
    name: "API:Contract:Plugin Loader Tests"
    env:
      CONTRACT_TYPE: "plugin-loader"
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start stack
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env
          echo CONTRACT_TYPE=${{ env.CONTRACT_TYPE }} >> .env
          docker compose --env-file ./.env -f ${{ env.FILE }} up --exit-code-from newman
        
      - name: Stop stacks
        if: always()
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker compose -f ${{ env.FILE }} down 

  raw-parser:
    name: API:Contract:Raw Parser Tests"
    env:
      CONTRACT_TYPE: "raw-parser"
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start stack
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker compose -f ${{ env.FILE }} up parser newman --exit-code-from newman
        
      - name: Stop stacks
        if: always()
        shell: bash
        run: |
          cd ${{ env.WORKDIR }}
          docker compose -f ${{ env.FILE }} down