name: Test and Deploy

on:
  push: 
  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:

  # LINTING
  lint:
    secrets: inherit
    uses: ./.github/workflows/job.lint.yml

  # TESTING
  api-test:
    secrets: inherit
    uses: ./.github/workflows/api.job.contract-test.yml

  web-test:
    secrets: inherit
    uses: ./.github/workflows/web.job.test.yml

  # VERSIONING
  versioning:
    needs: [api-test, web-test]
    if: ${{ needs.api-test.result == 'success' || needs.web-test.result == 'success' }}
    secrets: inherit
    uses: ./.github/workflows/job.version.yml

  # DEPLOYMENTS
  api-deploy:
    needs: [versioning]
    secrets: inherit
    uses: ./.github/workflows/api.job.deploy-cloudrun.yml

  docs-deploy:
    needs: [versioning]
    secrets: inherit
    uses: ./.github/workflows/docs.job.deploy.yml
    with:
      version: ${{ needs.versioning.outputs.version }}

  # web-deploy:
  #   needs: api-deploy
  #   secrets: inherit
  #   uses: ./.github/workflows/interfaces.web.deploy.yml

  create-pr:
    needs: [api-deploy, docs-deploy, versioning]
    if: ${{ needs.api-deploy.result == 'success' || needs.docs-deploy.result == 'success' }}
    secrets: inherit
    uses: ./.github/workflows/create-pr.yml
    with:
      version: ${{ needs.versioning.outputs.version }}