name: Test and Deploy

on:
  push: 
  workflow_dispatch:
    inputs:
      migration_input:
        description: 'Perform Migration'
        default: false
        required: true
        type: boolean
      seed_input:
        description: 'Perform Seed'
        default: false
        required: true
        type: boolean

jobs:

    # TESTING
    api-contract-test:
      secrets: inherit
      uses: ./.github/workflows/api.job.contract-test.yml

    # web-test:
    #   secrets: inherit
    #   uses: ./.github/workflows/interfaces.web.test.yml


    
    # VERSIONING
    versioning:
      needs: [api-contract-test]
      secrets: inherit
      uses: ./.github/workflows/versioning.yml

    # # DEPLOYMENTS
    # api-deploy:
    #   needs: [api-contract-test]
    #   secrets: inherit
    #   uses: ./.github/workflows/api.job.deploy-cloudrun.yml

    # docs-deploy:
    #   secrets: inherit
    #   uses: ./.github/workflows/docs.job.deploy.yml

    # web-deploy:
    #   needs: api-deploy
    #   secrets: inherit
    #   uses: ./.github/workflows/interfaces.web.deploy.yml

    # pull-request:
    #   needs: 
    #     - api-deploy
    #     # - web-deploy
    #     # - versioning
    #   secrets: inherit
    #   uses: ./.github/workflows/api.job.create-pr.yml