name: Versioning

on:
  push:
    branches:
      - 'develop'
      - 'test'
      - 'production'
      - 'main'
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:
  workflow_call: 

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false
  
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get version
        id: get_version
        run: |
          VERSION=$(npx release-it --ci --dry-run | grep "New version" | awk '{print $NF}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Output version
        run: 'echo "Version determined: ${{ env.VERSION }}"'