name: Versioning

on:
  workflow_call: 
    outputs:
      version:
        description: "The determined version"
        value: ${{ jobs.determine-version.outputs.version }}

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up minimal package.json
        run: |
          echo '{
            "name": "temporary-lib",
            "version": "0.0.0-release-it"
          }' > package.json

      - name: Install dependencies
        run: npm install @release-it/conventional-changelog conventional-changelog-angular

      - name: Get version
        id: get_version
        run: |
          VERSION=$(npx release-it --ci --release-version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Output version
        run: 'echo "Version determined: ${{ steps.get_version.outputs.version }}"'