name: "Web: Lint & Test"

on:
  push: 
    paths:
      - apps/interfaces/web/**/*
  workflow_call:
  workflow_dispatch:
    
jobs:
  smoke-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('apps/interfaces/web/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/interfaces/web

      - name: Cache Playwright browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('apps/interfaces/web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: apps/interfaces/web
      
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: apps/interfaces/web